### PR TITLE
Update right.goggles

### PR DESCRIPTION
**Pull request by spmedia**
REMOVE

/r/The_Donald/$boost=3,site=reddit.com

this sub is no longer a thing after being shut down by the reddit admins and reddit purged all of its content. 

Any attempt to visit an old URL or content will bring you to a "This community has been banned" page, example: https://old.reddit.com/r/The_Donald/comments/7fa8kg/do_white_men_really_deserve_to_vote/

REMOVE

/r/Conservative/$boost=3,site=reddit.com

This is a duplicate entry of the one right above it:
/r/conservative/$boost=3,site=reddit.com

### CODE REVIEW

**Comment by spmedia** [comment]
Additional ones you can add in if you wanted:

/r/AskTrumpSupporters/$boost=3,site=reddit.com
/r/prolife/$boost=3,site=reddit.com
/r/Republican/$boost=3,site=reddit.com
/r/benshapiro/$boost=3,site=reddit.com
/r/conservatives/$boost=3,site=reddit.com

**Comment by spmedia** [comment]
dang. Any reason why or are you just fixing this in a future update?

**Comment by adamking** [comment]
Apologies for closing this pull request out without comments! First, thank you for your great feedback! We are still working on these lists to more accurately reflect the AllSides Media Bias Chart. I will send your suggestions to the editorial team and let them know that some of the reddit links are outdated!

Thanks again for your input!

- Adam

**Comment by lewisje** [comment]
Maybe I should have looked for even the closed PRs before submitting mine; still, this had some good ideas for my fork; @spmedia, do you have some good suggestions for subreddits likely to be rated Center?

**Comment by spmedia** [comment]
> Maybe I should have looked for even the closed PRs before submitting mine; still, this had some good ideas for my fork; @spmedia, do you have some good suggestions for subreddits likely to be rated Center?

For centrist subs, I got you fam:

 - /r/NeutralPolitics/
 - /r/moderatepolitics/
 - /r/centrist/
 - /r/neutralnews

**Comment by lewisje** [comment]
FWIW, moderatepolitics was in the Left goggle, which is why I didn't pick the obvious subreddit names.

**Pull request closed without merging**
